### ISSUE TITLE
Question about the algorithm 

### ISSUE THREAD

**Issue by faalatawi** [nlpub/chinese-whispers-python#34]
Hello,

I have a question about the Chinese Whisper (CW) algorithm. How does it differ from the Label Propagation Algorithm (LPA)? which is implemented by [NetworkX](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.community.label_propagation.asyn_lpa_communities.html#networkx.algorithms.community.label_propagation.asyn_lpa_communities).

When should I use CW? and when LPA?

I'm working on a paper about community detection. and I appreciate the help.

**Comment by dustalov** [comment]
Hi, this is roughly the same algorithm independently discovered by different people from different areas of study. You can inspect the code to notice very similar computation steps.

The key difference between Chinese Whispers and other algorithms is the possibility of specifying the label weighting approach in node neighborhoods. It allows adjusting the way the dominant class is selected.

In `top` weighting, CW is equivalent to LPA. Our experience in studying language graphs shows that linear (`lin`) and logarithmic (`log`) weighting approaches fit these kinds of data better. Indeed, one has to tune this hyper-parameter on the specific dataset.

**Comment by faalatawi** [comment]
Thank you so much for the answer
