### ISSUE TITLE
Conda forge package

### ISSUE THREAD

**Issue by cbr9** [nlpub/chinese-whispers-python#36]
Would it be possible to install `chinese-whispers` through anaconda? Perhaps through conda-forge?

**Comment by dustalov** [comment]
Not yet, but we’ll be happy to submit it there if there is an instruction and the necessary configuration. I’d be happy to accept the corresponding pull request.

**Comment by dustalov** [comment]
https://github.com/conda-forge/staged-recipes/pull/21495

**Comment by dustalov** [comment]
Soon, it will be a part of conda-forge: https://github.com/conda-forge/chinese-whispers-feedstock.
